name: Go CI/CD

on:
  push:
    branches:
      - main
  pull_request:
  # Для публикации по тегу:
  release:
    types: [published]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21" # или ваша версия Go

      - name: Install dependencies
        run: go mod download

      - name: Lint
        run: go vet ./...

      - name: Run tests
        run: go test -v ./...

  docker:
    name: Build & Push Docker
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Получить имя тега из GitHub Release
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/your-repository:${{ github.event.release.tag_name }}
